### ISSUE TITLE
ReadTimeout is misleading, and more

### ISSUE THREAD

**Issue by sabhiram** [pires/go-proxyproto#1]
**Scenario:**
You have a server that is supposed to handle both proxy and non proxy type connections. You also have payloads which might be 2-4 bytes of significant data. The way you have your timeout code:
1. `<-time.After` will leak memory if it does not fire, and over time this will suck 
2. You return an error nicely after the timeout, but you still are not going to give up the Read on the connection until you see at-least 5 bytes! (or is it 12?) 

**My w/a:**
I simply set a ReadDeadline for my duration needed and use your blocking Read which should propagate an error as expected. This can still be ugly if the timing becomes unfortunate, but seems to work for the time being. Long term, I intended to re-write the bits that concern our application, but I felt this library could be beefed up a little more.

**Proposal**
Could you at-least add the code to peek only one byte and if that does not match, give up and bail? This would be immediately useful for clients who connect and have very low packet sizes.

The `<-time.After` thing is a personal gripe of mine. It should have no place in server code unless you are 100% sure that it will either (1) fire or (2) your program will exit. It should never be part of a case statement like that. See this group thread: https://groups.google.com/forum/#!topic/golang-nuts/A597Btr_0P8

**Comment by pires** [comment]
@sabhiram thanks for your feedback, truly appreciated. PR incoming, please review.

**Comment by pires** [comment]
Leaking timer fixed by bac3218.
Improved speed on header parsing for non-PROXY headers by 08ddf1a.

**Comment by sabhiram** [comment]
Looks good to me :) Thank you for the prompt fixes!
