### ISSUE TITLE
May I get full tcp header from fasthttp.RequestCtx?

### ISSUE THREAD

**Issue by auxo86** [pires/go-proxyproto#100]
Hi there,
I want to write a middleware for fiber (fasthttp based framework). May I get full tcp header from fasthttp.RequestCtx?
Many thanks.

**Comment by pires** [comment]
Hello. I am clueless. Maybe ask fasthttp folks? Good luck.

**Comment by auxo86** [comment]
I m sorry, it's my fault😆

**Comment by auxo86** [comment]
In fact, I want to integrate this package into fasthttp, however, I can't read tcp header correctly when using fasthttp.
Would you like to help me do it?
