### ISSUE TITLE
SourceChecker support?

### ISSUE THREAD

**Issue by jefferai** [pires/go-proxyproto#16]
Hi @pires ,

I know you created this after wanting v2 support in armon/go-proxyproto and it looks like this library is pretty well thought out. I'd love to have some projects at HC use this for the v2 support but one thing we rely on is the ability to do callbacks for making decisions -- see https://godoc.org/github.com/armon/go-proxyproto#SourceChecker

Not saying that is the correct interface necessarily (in particular it should probably take in and write out structs so that we can add other parameters to help make better decisions), but would you be amenable to something like that in this library?

**Comment by pires** [comment]
Hey @jefferai. Totally! And I think that's what we're aiming for in #11. Maybe you could chime in and work together w/ the PR owner?

**Comment by pires** [comment]
Fixed by https://github.com/pires/go-proxyproto/pull/11
