### ISSUE TITLE
Please add the leading v to the next release tag

### ISSUE THREAD

**Issue by drakkan** [pires/go-proxyproto#23]
The leading v is [required](https://github.com/golang/go/wiki/Modules) for modules:

"""
Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions
"""

thanks for this great library!

**Comment by pires** [comment]
🤦 sorry

**Comment by pires** [comment]
`v0.1.3` is out, thanks for reporting!

**Comment by pires** [comment]
https://github.com/pires/go-proxyproto/releases/tag/v0.1.3

**Comment by drakkan** [comment]
Thank you for the quick fix!
