### ISSUE TITLE
RemoteAddr from upstream

### ISSUE THREAD

**Issue by navossoc** [pires/go-proxyproto#24]
Is it possible to get the upstream remote address?

https://github.com/pires/go-proxyproto/blob/7e550d33f6da67842d921e49cbba0f5648a72cce/protocol.go#L141

As far I can tell reading the docs and the code, if the PROXY PROTOCOL is enabled we can't get the upstream IP anymore.

Is that right?

**Comment by pires** [comment]
Correct.

**Comment by navossoc** [comment]
Any chance of this getting exposed or do I need to make my own changes?

Thanks.

**Comment by pires** [comment]
I suggest you go with your own changes and open a PR if you'd like so that I can take a look.
