### ISSUE TITLE
Convenient way (example) how to use tlvparse functions with proxyproto.Conn

### ISSUE THREAD

**Issue by timson** [pires/go-proxyproto#26]
I have question about way to use tlvparse subpackage. I need to use SSL functions from tlvparse package to fetch SSL related info from header. It takes []proxyproto.TLV as argument, so my question is what the right way to get []proxyproto.TLV from proxyproto.Conn struct? My problem is that header field unexported in proxyproto.Conn struct and I can not access it from my app. May be I do something wrong, or misunderstand something, any idea, comments, suggestion? Thanks!

**Comment by pires** [comment]
Sorry, I totally missed this. I think you're right and you won't be able to do it without forking the library and implementing custom code. Since you're closing the issue, did you find a solution?

**Comment by timson** [comment]
No problem at all ) Yes, I did exactly what you said, I forked library and implement custom Header function on proxyproto.Conn to get header, and it was enough for me, after that I got tlvs and able to parse it. Thanks!
