### ISSUE TITLE
Give constants a type

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#28]
Right now it's not easy to tell that UNSPEC/TCPv4/etc are `AddressFamilyAndProtocol`. Somethign like this would help:

```go
const (
	UNSPEC      AddressFamilyAndProtocol = '\x00'
	TCPv4       AddressFamilyAndProtocol = '\x11'
	…
)
```

**Comment by pires** [comment]
Makes sense. Please, go ahead and open a PR! Glad to review.
