### ISSUE TITLE
An example for a Dialer and Listener is required.

### ISSUE THREAD

**Issue by elico** [pires/go-proxyproto#3]
This is a really good library but it's missing examples for a Dialer and a Listener.
IE client and a server service.
I might write one and I was thinking about a simple "echo" client and server.

The server would accept a PROXY TCP protocol connection and will echo back(and log to stdout) if possible the request protocol(TCP4\TCP6 only), src and destination IP:PORT.

The client would open a connection to a PROXY enabled server(Listener) with a specific src and destination IP:PORT (TCP4\TCP6) and will receive the into the socket\connection a line of readable text containing the received IP:PORT.

I have seen an implementation of this but I forgot to save the links so I cannot copy and paste it and I will need to use some CPU to write it.
Any recommendations on where to start?

I have seen this implementation but it's still not sitting well for me
- https://github.com/Freeaqingme/go-proxyproto/blob/master/protocol.go

Other examples:
- https://github.com/armon/go-proxyproto
- https://github.com/kennylevinsen/serve2d
- https://github.com/nabeken/mikoi/blob/master/mikoi.go
- https://github.com/ninchat/go-proxyprotocol
- https://github.com/inkel/viaproxy/blob/master/conn.go
- https://github.com/djmaze/proxy-responder/blob/master/main.go

I wrote a TPROXY Server and Library in golang at:
- https://github.com/elico/go-linux-tproxy

Which has a basic TCP proxy server function that can eventually utilize the PROXY protocol in couple environments.

**Comment by elico** [comment]
@pires couple examples and utilities at:

- http://gogs.ngtech.co.il/elicro/proxy-protocol-examples

I will try to add there another example which uses TPROXY later on

**Comment by anisse** [comment]
Hi @pires ! I've published my listener here: https://github.com/anisse/proxylistener/blob/master/proxylistener.go ; I'd really like it to be used as an example in this library, so I was wondering how to proceed ?
 - should it need a full program that shows how to use it or is the README sufficient ?
 - should it go into the examples/ directory ? What if we want people to use it directly ? Maybe contrib/listener ?
 - should it be tested ? How ? With a server counterpart ?

What am I missing?

**Comment by elico** [comment]
@anisse I have just written two proxies from TCP to SCTP and from SCTP to TCP at:
- http://gogs.ngtech.co.il/NgTech-LTD/sctp-proxies

I believe that a GoLang programmer should have the fundamentals to understand what a listener and a dialer is but a good and practical example always helps these who doesn't fully grasp the subject.
In your usage example it's only a file server but a proxy server for both plain tcp and http might be a good idea.

I don't remember the project name but there is one which implements a TCP proxy like haproxy written in GoLang but without the PROXY protocol support.

**Comment by anisse** [comment]
@elico : I can't reach your website, and couldn't before either; *edit:* it took 4 minutes to load completely, 1m to load a source file with a hot cache.

I used an HTTP example because it was my usecase, and I think a likely one, and I agree the readme could use more examples, this is the type of feedback I was looking for.

Your examples are nice, but they don't appear in the list of public importers here: https://godoc.org/github.com/pires/go-proxyproto?importers ; I think it could be useful for anyone looking at usage examples.

Also, I think it's nice to understand net.Dialer and net.Listener, but should one have to write 70 lines of code before starting to use this package ?

**Comment by elico** [comment]
@anisse first try the next link:
- <http://faster.gogs.ngtech.co.il/>

my main link has slow uplink but this one has most of the time at-least 5Mbit upload while it depends on the whether and couple other factors such as the connection bandwidth plan consumption.
I have also verified that there was some setting which caused the traffic to move slower.
I hope it will work better for you.
Maybe I will upload the code to github later.

As for having to write 70 lines of code before starting to use this package...
From my perspective it's not a novice library and if the coder/programmer/researcher didn't wrote 70 lines yet then he or she should write basic programming to get familiar with the language and programming basics.

I believe  that your question is towards any reason examples should or shouldn't be out-there...
and I do agree that if presenting an example or a good example of usage can be provided without consuming too many resources then it should be provided but only as a good gesture.
I have seen more then once that providing a specific example or examples is the wrong thing to do while I am trying to give code examples.

**Comment by pires** [comment]
I think examples are a great thing to have but I'm just unable to find the time to commit to it atm. PRs to add [example tests](https://blog.golang.org/examples) are most welcome.

**Comment by elico** [comment]
> 
> 
> @elico : I can't reach your website, and couldn't before either; _edit:_ it took 4 minutes to load completely, 1m to load a source file with a hot cache.
> 
> I used an HTTP example because it was my usecase, and I think a likely one, and I agree the readme could use more examples, this is the type of feedback I was looking for.
> 
> Your examples are nice, but they don't appear in the list of public importers here: https://godoc.org/github.com/pires/go-proxyproto?importers ; I think it could be useful for anyone looking at usage examples.
> 
> Also, I think it's nice to understand net.Dialer and net.Listener, but should one have to write 70 lines of code before starting to use this package ?

I had a QOS issue and it was limiting the upload(your download) speed.
Now it seems to work much better.

**Comment by pires** [comment]
This was partially addressed in #8 but you can get more clarity by reading `protocol_test.go`.

**Comment by pires** [comment]
Hey @igorwwwwwwwwwwwwwwwwwwww, maybe you'd like to contribute a snippet of your TLS listener use-case, which originated #21? That would be awesome!
