### ISSUE TITLE
Unix socket addresses missing from Header

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#34]
`Header` only supports IP addresses. However the Unix socket header is defined as such:

```c
        struct {        /* for AF_UNIX sockets, len = 216 */
             uint8_t src_addr[108];
             uint8_t dst_addr[108];
        } unix_addr;
```

**Comment by pires** [comment]
I totally overlooked this and, unfortunately, changing it at this point would result in a API breaking change. The only thing that can be done is to add two attributes specifically for this or break the API and release a major change to the lib. I'm divided. Suggestions?

**Comment by emersion** [comment]
Maybe we can start with adding two fields, and try to come up with something better once we have more breaking changes in mind?

**Comment by pires** [comment]
Guess we're all trying to avoid a major release of the lib that would make Go versioning complicated, so yeah, maybe.

**Comment by emersion** [comment]
This library is still unstable (0.X), so releasing a new 0.3 version would allow for breaking changes anyways.

See https://blog.golang.org/publishing-go-modules:

> If you add to the public API, make a breaking change to a v0 module, or upgrade the minor or version of one of your dependencies, increment the MINOR version for your next release.

**Comment by pires** [comment]
I'm divided. Let's introduce the breaking change to master and decide later what to do in terms of release.

**Comment by pires** [comment]
Well, given #42 is a breaking change why not just go ahead and address this too? Setting milestone for 0.3.0.
