### ISSUE TITLE
Header.{Local,Remote}Addr always return a TCP address

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#43]
TCP is hard-coded regardless of the `TransportProtocol`: https://github.com/pires/go-proxyproto/blob/3e7e0f55e48bb58288f1716a88770db96bfc342d/header.go#L111

**Comment by pires** [comment]
I'm wondering if we should fix this in a 0.2.x branch 🤔

**Comment by pires** [comment]
Actually, this is on purpose as it's an implementation detail. The function returns the interface `net.Addr`.

**Comment by emersion** [comment]
Yes, the API is fine. The implementation isn't though, since the v2 header can parse non-TCP addresses. So for instance `TransportProtocol` could be `UDP6` and `LocalAddr` would still return a `net.TCPAddr`.

**Comment by pires** [comment]
This seems to be expected for V1 as discussed in #45. I'm open to change this for V2.
