### ISSUE TITLE
Header v1 parsing code doesn't support UDP/Unix addresses

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#45]
The v1 parsing and formatting code will parse UDP and Unix addresses as UNSPEC.

**Comment by pires** [comment]
Can you link me directly to the offending code?

**Comment by emersion** [comment]
Sure! Here's where the parsing happens (only accounts for TCP4 and TCP6):

https://github.com/pires/go-proxyproto/blob/528b59d6162fc5463728b0e48a5ff5e73151eb38/v1.go#L37

And here's where the formatting happens (same):

https://github.com/pires/go-proxyproto/blob/528b59d6162fc5463728b0e48a5ff5e73151eb38/v1.go#L71

**Comment by pires** [comment]
This seems to follow the assumption
https://github.com/pires/go-proxyproto/blob/528b59d6162fc5463728b0e48a5ff5e73151eb38/v1.go#L68-L69

**Comment by pires** [comment]
I just re-read the spec and the comment above comes from it. And more
```

2.2. Binary header format (version 2)

(...)
It was also not possible to specify address families outside
IPv4/IPv6 nor non-TCP protocols.
```

That said, I think this can be closed as UDP and Unix sockets don't seem to be supported in V1.

**Comment by emersion** [comment]
Oops. Indeed, I just assumed v1 supported these features, but doesn't seem like it.
