### ISSUE TITLE
Release notes for 0.3.0

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#47]
This is a meta issue to plan the next breaking release.

## Breaking changes

- Rely on `net.Addr`, which allows to represent any network address, instead of using an IP and a port (#46)

  The Header.{Local,Remote}Addr methods are removed since users can now
  just access Header.{Source,Destination}Addr.

  New helpers (`header.{TCPAddrs(),UDPAddrs(),UnixAddrs(),IPs(),Ports()}`) allows to
  easily extract data from `net.Addr` attributes.

  The `header.{Local,Remote}Addr` helpers have been removed in favor or accessors `header.{Source,Destination}Addr`.
- `TLV.Length` has been removed, in favor of using `len(TLV.Value)` instead (#42)

## Improvements

- Properly validate source and destination IPs when transport protocol is IP-based, e.g. ensure IPv4 addresses when TCPv4 is set (#46 and #48)
- Support Unix sockets (#46)
- Format a PP2SSL struct into a TLV (#41)
- Test Go 1.14 and 1.15 support (#39)
- Update spec URL (#40)

**Comment by pires** [comment]
Thank you for starting this, @emersion. I have edited to include some more changes.

**Comment by pires** [comment]
@emersion if you agree w/ all of the above, I'll cut a release after I'm done w/ day job stuff.

**Comment by emersion** [comment]
Yes, all of this LGTM!

**Comment by pires** [comment]
On it!

**Comment by emersion** [comment]
0.3.0 is released :tada:

https://github.com/pires/go-proxyproto/releases/tag/v0.3.0
