### ISSUE TITLE
Export underlying connection

### ISSUE THREAD

**Issue by mschneider82** [pires/go-proxyproto#50]
Hi,

It would be good to export the underlying `proxyproto.Conn.conn` connection. 
Since proxyproto.Conn is not an `net.TCPConn`, and I need to cast it.

**Comment by pires** [comment]
Where can we find `tcp.WriterCloser`?

**Comment by mschneider82** [comment]
I fixed my comment. We cannot cast a Conn from this package to net.TCPConn that's why I need the underlying net.conn where the cast is possible (if it's a TCP conn)

**Comment by pires** [comment]
https://github.com/pires/go-proxyproto/releases/tag/v0.3.1
