### ISSUE TITLE
support tls？

### ISSUE THREAD

**Issue by smil267** [pires/go-proxyproto#59]
hi, when the server listen mode is tls, it isn't work. can you support tls listen?

**Comment by smil267** [comment]
tls prompt err:
tls: first record does not look like a TLS handshake

**Comment by pires** [comment]
I'm sorry but I can't understand what the request is here. TLS is supported. Can you share code?

**Comment by pires** [comment]
Here's [a test](https://github.com/pires/go-proxyproto/blob/main/protocol_test.go#L621-L676) that shows how to setup TLS properly. Let us know if it doesn't work. Closing for now.

**Comment by baixiaoshi** [comment]
![image](https://user-images.githubusercontent.com/5595933/181145256-90d8bc17-269a-4e19-8cda-6cdb201cced4.png)


server code

`func main() {

    cert, err := tls.LoadX509KeyPair("cert/xxxx.crt", "cert/xxx.key")
    if err != nil {
        log.Println(err)
        return
    }
    config := &tls.Config{
        Certificates: []tls.Certificate{cert}}

    ln, err := tls.Listen("tcp", ":9090", config)

    proxyListener := &proxyproto.Listener{
        Listener: ln,
    }

    conn, err := proxyListener.Accept()
    if err != nil {
        log.Fatalf("err: %v", err)
    }
    defer conn.Close()

    addr := conn.RemoteAddr().(*net.TCPAddr)
    fmt.Println("ip====", addr.IP.String())
    if addr.IP.String() != "10.1.1.1" {
        log.Fatalf("bad: %v", addr)
    }
    if addr.Port != 1000 {
        log.Fatalf("bad: %v", addr)
    }
}
`


client code

`func main() {

    conn, err := net.Dial("tcp", "127.0.0.1:9090")
    if err != nil {
        log.Fatalf("err: %v", err)
    }
    defer conn.Close()

    // Write out the header!
    header := "PROXY TCP4 10.1.1.1 20.2.2.2 1000 2000\r\n"
    conn.Write([]byte(header))

}`

**Comment by shanezhiu** [comment]
I got the same error.
