### ISSUE TITLE
Parsing v2 UNSPEC and v1 PROXY UNKNOWN not implemented

### ISSUE THREAD

**Issue by bohanyang** [pires/go-proxyproto#60]
Hi! I found that this library is missing the ability to parse these two kinds of header, which are required by the protocol and mandatory to implement, while trying to resolve XTLS/Xray-core#166

### v2 UNSPEC

When this header is received:

```
0d 0a 0d 0a 00 0d 0a 51 55 49 54 0a 20 00 00 00
```

which is <v2 signature> + LOCAL command (\x20) + UNSPEC address family UNSPEC protocol (\x00)
`ErrUnsupportedAddressFamilyAndProtocol` is returned
https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/v2.go#L85-L87
This is because UNSPEC is absent in supportedTransportProtocol 
https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/addr_proto.go#L6-L23
This UNSPEC header is used when HAProxy doing health checks, or the proxied client is requesting via a unix socket.
Also the protocol spec says:

```
Only the UNSPEC protocol byte (\x00) is mandatory to implement on the receiver.
A receiver is not required to implement other ones, provided that it
automatically falls back to the UNSPEC mode for the valid combinations above
that it does not support.
```

### v1 PROXY UNKNOWN

When header `PROXY UNKNOWN\r\n` is received,
https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/v1.go#L25-L33
returns ErrCantReadProtocolVersionAndCommand.
This is because in this case, there's only 2 parts separated by spaces, instead of 6 parts as `PROXY <PROTO> <SRC_ADDR> <DEST_ADDR> <SRC_PORT> <DEST_PORT>`
The protocol spec says:
```
If the announced transport protocol is "UNKNOWN", then the receiver knows that
the sender speaks the correct PROXY protocol with the appropriate version, and
SHOULD accept the connection and use the real connection's parameters as if
there were no PROXY protocol header on the wire.
```
Also, this kind of header can be formatted by the library.
https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/v1.go#L76-L88

Although I really don't know much about Golang, I'll try my best to support you to resolve this issue. Thanks!

**Comment by pires** [comment]
Thank you for the detailed issue description.

I think I can do this, however the spec seems to have changed under our feet, ie
```
Note that an earlier version of this specification suggested to use this when sending health checks,
but this causes issues with servers that reject the "UNKNOWN" keyword. Thus is it
now recommended not to send "UNKNOWN" when the connection is expected to
be accepted, but only when it is not possible to correctly fill the PROXY line.
```

**Comment by bohanyang** [comment]
Thank you. I admit that UNKNOWN is not something recommended, but there ARE cases that "it is not possible to correctly fill the PROXY line", for example when using unix socket or even abstract domain docket with HAProxy. IMO we should implement it as this is a generic library.

**Comment by pires** [comment]
For v2, I'll add support for UNSPEC but only when LOCAL is set. The spec is clear the receiver can reject the unsupported stuff. Do you have a different interpretation?

**Comment by bohanyang** [comment]
Yeah, it's OK to restrict UNSPEC to LOCAL only.

**Comment by pires** [comment]
PR to fix this is open. Will wait a few days for feedback, if that's ok.

**Comment by pires** [comment]
Are you able to try it @bohanyang or provide me with reproducible steps?

**Comment by bohanyang** [comment]
I'll test it later with Xray-core. You can reproduce it by create a server listening on a unix socket and put HAProxy in front of it:
```
frontend inbound
  bind :5678
  bind unix@/tmp/haproxy.sock
  default_backend outbound

backend outbound
  server proxyproto unix@/tmp/test.sock send-proxy-v2 check
```

**Comment by bohanyang** [comment]
Tested and the library's issue seems fixed!

**Comment by pires** [comment]
Superb! Merging and releasing 0.4.0 🎉
