### ISSUE TITLE
LICENSE missing copyright line

### ISSUE THREAD

**Issue by tecnobrat** [pires/go-proxyproto#63]
Hey pires,

Looks like your LICENSE file does not have the filled in Copyright line:

https://github.com/pires/go-proxyproto/blob/bf52da6cb616948e69e6c448d7c1193875ae49e3/LICENSE#L189

Looks like it needs your name and the year filled in.  I'm trying to see if I can include this library into https://github.com/fabiolb/fabio to add proxy v2 support to that project but I need to know the correct copyright line as per their contribution guidelines on attributions :)

Thanks!

**Comment by pires** [comment]
Hey @tecnobrat! Thanks for reporting. Let's see what I can do in right now.
