### ISSUE TITLE
[Security] Workflow test.yml is using vulnerable action shogo82148/actions-goveralls

### ISSUE THREAD

**Issue by Freakston** [pires/go-proxyproto#85]
The workflow test.yml is referencing action shogo82148/actions-goveralls using references v1.2.2. However this reference is missing the commit [93213fdb0bf003e512edcc55e1bdca000f7e4d65](https://github.com/shogo82148/actions-goveralls/commits/93213fdb0bf003e512edcc55e1bdca000f7e4d65) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by pires** [comment]
Thanks for the report. I fixed it in https://github.com/pires/go-proxyproto/commit/b46edfef182cdbc31b664ce6ab4b70d487c22e9f#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L39
