### ISSUE TITLE
Example HTTP server code doesn't support HTTP/2 upgrade

### ISSUE THREAD

**Issue by emersion** [pires/go-proxyproto#90]
`net/http` can't access `PP2_TYPE_ALPN` which is necessary for the HTTP/2 upgrade.

Some manual logic is necessary to handle HTTP/2 upgrades, e.g. https://git.sr.ht/~emersion/kimchi/tree/master/item/server.go#L175

Would it be desirable to host this glue code in go-proxyproto so that users can easily fire up an HTTP server with HTTP/2 upgrade support?

**Comment by pires** [comment]
Would it be enough to introduce a new example app in the `examples` folder?

**Comment by emersion** [comment]
The boilerplate is annoying to type, so I'd prefer to have it in the lib somehow.
