### ISSUE TITLE
Nginx proxy_protocol doesn't work.

### ISSUE THREAD

**Issue by LaikeeDu** [pires/go-proxyproto#94]
Hi, I've used Nginx as a load balance, and use example/server or example/http as backend.
But I can't get real IP from nginx even if I have used the configuration of Nginx like `proxy_protocol      on`
```
stream {

upstream my_servers{
#least_conn;
server 1.2.3.4:22;
#proxy_protocol      on;
}
server {
listen [::]:223 ipv6only=off;
listen [::]:223 ipv6only=off udp;
proxy_pass my_servers;
proxy_protocol      on;

}
}
```

The error was: `proxyproto: invalid address` or it just give me the IP of Nginx.
Because I didn't find any thing relative to the problem, so I open the issue asking you for help.
I will be appreciate if you can look deep into the problem.

**Comment by pires** [comment]
I'm sorry but I'm not able to help with this for the time being. I've labeled the issue hoping someone will take a stab at it.

**Comment by pires** [comment]
@himgoods in such case is traffic signaled as IPv6, eg TCPv6?

**Comment by drakkan** [comment]
> @himgoods in such case is traffic signaled as IPv6, eg TCPv6?

yes, it si signaled as IPv6. I used this configuration to test my patch

```
stream {
    server {
        listen              [::]:2222 ipv6only=off;
        #listen              2222;

        proxy_pass          127.0.0.1:2022;
        proxy_protocol      on;
    }
}
```

**Comment by pires** [comment]
Thank you, @drakkan.
