### ISSUE TITLE
Set-up automated releases

### ISSUE THREAD

**Issue by pires** [pires/go-proxyproto#98]
Rely on Github Actions, such as https://github.com/softprops/action-gh-release, to automatically create releases based on tags.

**Comment by drakkan** [comment]
I prefer to use [gh release create](https://cli.github.com/manual/gh_release_create) directly. See [here](https://github.com/drakkan/sftpgo/blob/main/.github/workflows/release.yml#L598).

I had some problems with the above action, but that was a long time ago, I don't remember exactly what and it could be fixed now.

**Comment by pires** [comment]
Thanks for sharing but I prefer a Github Action which purpose is to cut releases rather than calling CLI(s), if it can be avoided.
